DEFAULT_PAGE_WIDTH_PT = 595.2
DEFAULT_PAGE_HEIGHT_PT = 841.8

DEFAULT_MARGIN_TOP_PT = 72
DEFAULT_MARGIN_RIGHT_PT = 72
DEFAULT_MARGIN_BOTTOM_PT = 72
DEFAULT_MARGIN_LEFT_PT = 72

DEFAULT_FONT_SIZE_PT = 1
PARAGRAPH_SPACING_PT = 6
EMPTY_LINE_SPACING_PT = 12

CHAR_WIDTH_FACTOR = 0.6
LINE_HEIGHT_FACTOR = 1.2
BOLD_FONT_FACTOR = 1.1
